title: Engineered Meta-Cognitive Workflow Architecture for Windsurf
description: A sophisticated meta-prompt framework for Windsurf AI IDE
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag

# Show downloads button
show_downloads: true

# Logo path (using the EASAI logo)
logo: /assets/img/logo.png

# Additional settings
lang: en-US
author:
  name: Shawn McAllister
  url: https://x.com/entrepeneur4lyf

# Social media (for SEO)
social:
  name: Shawn McAllister
  links:
    - https://x.com/entrepeneur4lyf
    - https://github.com/entrepeneur4lyf
